# Linux and macOS
brew "bash"
brew "git"
brew "zsh"

# macOS only
if OS.mac?
    brew "mas"

    cask "obsidian"
    cask "tailscale-app"
end

# specific machines
case ENV["DOTFILES_MACHINE"]
when "machine-name"
else
end
