# Bash

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

# Go

[language-server.gopls.config]
gofumpt = true

[[language]]
name = "go"
auto-format = true
formatter = { command = "gofumpt" }

[[language]]
name = "gomod"
auto-format = true
formatter = { command = "gofumpt" }

# YAML

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }
auto-format = true

# Python

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

# TypeScript

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

# TOML

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

# JSON

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = true

# Markdown

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true