# Bash

[[language]]
name = "bash"
auto-format = true

[language.indent]
tab-width = 4
unit = "    "

[language.formatter]
command = "shfmt"
args = ["-i", "4"]

# Go

[[language]]
name = "go"
auto-format = true

[language.formatter]
command = "gofumpt"

[[language]]
name = "gomod"
auto-format = true

[language.formatter]
command = "gofumpt"

# YAML

[[language]]
name = "yaml"
auto-format = true

[language.formatter]
command = "prettier"
args = ["--parser", "yaml"]

# Python

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true

[language.formatter]
command = "ruff"
args = ["format", "-"]

# TypeScript

[[language]]
name = "typescript"
auto-format = true

[language.formatter]
command = "prettier"
args = ["--parser", "typescript"]

# TOML

[[language]]
name = "toml"
language-servers = ["tombi"]
auto-format = true

[language.formatter]
command = "tombi"
args = ["format", "-"]

# JSON

[[language]]
name = "json"
auto-format = true

[language.formatter]
command = "prettier"
args = ["--parser", "json"]

# Rust

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true

[language.formatter]
command = "rustfmt"
args = ["--edition", "2021"]

# Markdown

[[language]]
name = "markdown"
language-servers = ["markdown-oxide", "marksman"]
auto-format = true

[language.formatter]
command = "prettier"
args = ["--parser", "markdown"]

[language-server.gopls.config]
gofumpt = true
