gui:
  theme:
    activeBorderColor:
      - "#a6e3a1"   # Green
      - bold
    inactiveBorderColor:
      - "#a6adc8"   # Subtext0
    optionsTextColor:
      - "#89b4fa"   # Blue
    selectedLineBgColor:
      - "#313244"   # Surface0
    cherryPickedCommitBgColor:
      - "#45475a"   # Surface1
    cherryPickedCommitFgColor:
      - "#cba6f7"   # Mauve
    unstagedChangesColor:
      - "#f38ba8"   # Red
    defaultFgColor:
      - "#cdd6f4"   # Text
    searchingActiveBorderColor:
      - "#f9e2af"   # Yellow

git:
  pagers:
    - colorArg: always
      pager: delta --paging=never